---

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Remove some bad packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=absent
  with_items:
    - python-pip
  tags: packages

- name: Install non-version-specific Debian base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=present
  with_items:
    - apt-transport-https
    - build-essential
    - ntp
    - htop
    - sudo
    - curl
    - git
    - libjpeg-dev
    - libpq-dev
    - libffi-dev
    - python3
    - python3-dev
    - python3-pip
    - supervisor
  tags: packages

- name: Install Debian (Wheezy) packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=present
  with_items:
    - python-pycurl
  tags: packages
  when: ansible_distribution == "Debian" and ansible_distribution_release == "wheezy"

- name: Install Debian (Jessie) packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=present
  with_items:
    - python3-pycurl
  tags: packages
  when: ansible_distribution == "Debian" and ansible_distribution_release == "jessie"

- name: Install Ubuntu packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=present
  with_items:
    - python3-pycurl
  tags: packages
  when: ansible_distribution == "Ubuntu"


- name: Install virtualenv
  pip: name=virtualenv executable="/usr/bin/pip3"
  tags: packages
